# Generated by Django 4.1.2 on 2022-12-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_crunch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=14),
        ),
    ]
