# Generated by Django 4.1.2 on 2022-12-28 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_crunch', '0002_alter_employee_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockcontent',
            name='empID',
        ),
        migrations.DeleteModel(
            name='CodeBlock',
        ),
        migrations.RemoveField(
            model_name='empsignhtml',
            name='empID',
        ),
        migrations.DeleteModel(
            name='BlockContent',
        ),
        migrations.DeleteModel(
            name='EmpSignHTML',
        ),
    ]
