# Generated by Django 4.1.2 on 2022-12-28 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_crunch', '0003_remove_blockcontent_empid_delete_codeblock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('title', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'content_type',
            },
        ),
        migrations.CreateModel(
            name='HeaderBlock',
            fields=[
                ('title', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'header_block',
            },
        ),
        migrations.CreateModel(
            name='code_block',
            fields=[
                ('title', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField()),
                ('empID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='code_crunch.employee')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='code_crunch.contenttype')),
            ],
            options={
                'db_table': 'code_block',
            },
        ),
    ]
