# Generated by Django 4.1.2 on 2022-12-28 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_crunch', '0004_contenttype_headerblock_code_block'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='code_block',
            new_name='CodeBlock',
        ),
    ]
