# Generated by Django 4.1.2 on 2022-12-29 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_crunch', '0005_rename_code_block_codeblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttype',
            name='title',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
