# Generated by Django 4.1.2 on 2022-12-29 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_crunch', '0007_alter_codeblock_title_alter_contenttype_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeblock',
            name='title',
            field=models.CharField(max_length=75, primary_key=True, serialize=False, unique=True),
        ),
    ]
